version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
jobs:
  build:
    docker:
      - image: 'circleci/node:16'
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: 'npm install'
      - cypress/run:
          record: true
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run:
          name: 'Cypress Automation'
          command: 'npm run e2e'   
      - run:
          name: 'Build Project'
          command: 'npm run build'